from collections.abc import Callable
import warnings
from typing import Any, Optional

import torch
from pyannote.audio import Audio, Pipeline


CUDA_8GB_SEGMENTATION_BATCH_SIZE = 32
CUDA_8GB_EMBEDDING_BATCH_SIZE = 7
LEGACY_BATCH_SIZE = 8
ProgressCallback = Callable[[dict[str, Any]], None]

# Suppress harmless PyTorch warning generated by pyannote.audio
warnings.filterwarnings("ignore", message="std\\(\\): degrees of freedom is <= 0")
warnings.filterwarnings("ignore", message=".*degrees of freedom.*")
# Cache the pipeline after first load so subsequent requests don't re-download
# and re-initialise the model weights (~1.5 GB) from scratch every time.
_pipeline: Optional[Pipeline] = None
_pipeline_token: Optional[str] = None


def diarize(
    audio_path: str,
    hf_token: str,
    min_speakers: Optional[int] = None,
    max_speakers: Optional[int] = None,
    progress_callback: Optional[ProgressCallback] = None,
) -> list[tuple[float, float, str]]:
    global _pipeline, _pipeline_token

    def report(
        phase: str,
        progress: float,
        message: str,
        *,
        completed: Optional[int] = None,
        total: Optional[int] = None,
    ) -> None:
        if progress_callback is None:
            return
        progress_callback(
            {
                "phase": phase,
                "progress": max(0.0, min(1.0, progress)),
                "message": message,
                "completed": completed,
                "total": total,
            }
        )

    # Reload only if the token changed (unlikely in practice, but safe).
    if _pipeline is None or _pipeline_token != hf_token:
        report("model_loading", 0.01, "Loading speaker diarization model...")
        _pipeline = Pipeline.from_pretrained(
            "pyannote/speaker-diarization-3.1",
            token=hf_token,
        )
        # Prefer NVIDIA CUDA on Windows/Linux, Apple Metal on macOS, then CPU.
        # Transcription is unloaded before diarization, so Pyannote can use the
        # best accelerator without competing with the Whisper engine for VRAM.
        if torch.cuda.is_available():
            device = torch.device("cuda")
        elif torch.backends.mps.is_available():
            device = torch.device("mps")
        else:
            device = torch.device("cpu")
        _pipeline.to(device)

        segmentation_batch_size = LEGACY_BATCH_SIZE
        embedding_batch_size = LEGACY_BATCH_SIZE
        if device.type == "cuda":
            total_vram = torch.cuda.get_device_properties(device).total_memory
            if total_vram <= 10 * 2**30:
                segmentation_batch_size = CUDA_8GB_SEGMENTATION_BATCH_SIZE
                embedding_batch_size = CUDA_8GB_EMBEDDING_BATCH_SIZE

        # These phase-specific FP32 batches avoid the measured batch-8
        # WeSpeaker/cuDNN memory cliff on 8 GiB NVIDIA GPUs. Other accelerators
        # retain the previous batch size until they have their own measured
        # hardware profiles.
        if hasattr(_pipeline, "segmentation_batch_size"):
            _pipeline.segmentation_batch_size = segmentation_batch_size
        elif hasattr(_pipeline, "_segmentation"):
            _pipeline._segmentation.batch_size = segmentation_batch_size

        if hasattr(_pipeline, "embedding_batch_size"):
            _pipeline.embedding_batch_size = embedding_batch_size

        _pipeline_token = hf_token
        report("model_loading", 0.08, "Speaker diarization model ready.")

    # Decode/resample once. Passing an in-memory waveform prevents Pyannote from
    # repeatedly seeking and decoding the file for segmentation and embeddings.
    report("audio_loading", 0.09, "Loading prepared audio for diarization...")
    waveform, sample_rate = Audio(sample_rate=16000, mono="downmix")(audio_path)
    audio = {"waveform": waveform, "sample_rate": sample_rate}
    report("audio_loading", 0.12, "Prepared audio loaded.")

    kwargs: dict = {}
    if min_speakers is not None:
        kwargs["min_speakers"] = min_speakers
    if max_speakers is not None:
        kwargs["max_speakers"] = max_speakers

    def pipeline_hook(
        step_name: str,
        _step_artifact: Any,
        _file: Any = None,
        completed: Optional[int] = None,
        total: Optional[int] = None,
        **_kwargs: Any,
    ) -> None:
        fraction = 0.0
        if completed is not None and total:
            fraction = completed / total

        if step_name == "segmentation":
            report(
                step_name,
                0.12 + (0.20 * fraction),
                "Detecting speech and speaker changes...",
                completed=completed,
                total=total,
            )
        elif step_name == "speaker_counting":
            report(step_name, 0.34, "Estimating the number of active speakers...")
        elif step_name == "embeddings":
            report(
                step_name,
                0.36 + (0.56 * fraction),
                "Extracting speaker embeddings...",
                completed=completed,
                total=total,
            )
        elif step_name == "discrete_diarization":
            report(step_name, 0.97, "Finalizing speaker labels...")

    diarization_result = _pipeline(audio, hook=pipeline_hook, **kwargs)
    report("complete", 1.0, "Speaker diarization complete.")

    # In pyannote-audio 4.x, the pipeline returns a DiarizeOutput object
    # instead of a raw pyannote.core.Annotation.
    # Newer pyannote releases expose an exclusive, non-overlapping view made
    # for assigning transcript timestamps to one speaker. Fall back cleanly
    # for older 3.x releases.
    if hasattr(diarization_result, "exclusive_speaker_diarization"):
        diarization = diarization_result.exclusive_speaker_diarization
    elif hasattr(diarization_result, "speaker_diarization"):
        diarization = diarization_result.speaker_diarization
    else:
        diarization = diarization_result

    return [
        (turn.start, turn.end, speaker)
        for turn, _, speaker in diarization.itertracks(yield_label=True)
    ]

def unload_diarizer():
    """Unload the Pyannote model and explicitly free PyTorch/Metal memory."""
    global _pipeline, _pipeline_token
    _pipeline = None
    _pipeline_token = None
    
    import gc
    gc.collect()
    
    # Explicitly clear Metal Performance Shaders (MPS) cache to instantly release GPU VRAM
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    elif torch.backends.mps.is_available():
        torch.mps.empty_cache()
