from typing import Optional
from pyannote.audio import Pipeline
import torch
import warnings

# Suppress harmless PyTorch warning generated by pyannote.audio
warnings.filterwarnings("ignore", message="std\\(\\): degrees of freedom is <= 0")
warnings.filterwarnings("ignore", message=".*degrees of freedom.*")
# Cache the pipeline after first load so subsequent requests don't re-download
# and re-initialise the model weights (~1.5 GB) from scratch every time.
_pipeline: Optional[Pipeline] = None
_pipeline_token: Optional[str] = None


def diarize(
    audio_path: str,
    hf_token: str,
    min_speakers: Optional[int] = None,
    max_speakers: Optional[int] = None,
) -> list[tuple[float, float, str]]:
    global _pipeline, _pipeline_token

    # Reload only if the token changed (unlikely in practice, but safe).
    if _pipeline is None or _pipeline_token != hf_token:
        _pipeline = Pipeline.from_pretrained(
            "pyannote/speaker-diarization-3.1",
            token=hf_token,
        )
        # The transcription engine is unloaded before diarization, so Pyannote
        # can use the best available Torch accelerator without competing for VRAM.
        if torch.cuda.is_available():
            _pipeline.to(torch.device("cuda"))
        elif torch.backends.mps.is_available():
            _pipeline.to(torch.device("mps"))
        else:
            _pipeline.to(torch.device("cpu"))
            
        
        # Pyannote >= 3.x/4.x exposes explicit properties for batch sizes
        if hasattr(_pipeline, 'segmentation_batch_size'):
            _pipeline.segmentation_batch_size = 8
        elif hasattr(_pipeline, '_segmentation'):
            _pipeline._segmentation.batch_size = 8
            
        if hasattr(_pipeline, 'embedding_batch_size'):
            _pipeline.embedding_batch_size = 8
            
        _pipeline_token = hf_token

    kwargs: dict = {}
    if min_speakers is not None:
        kwargs["min_speakers"] = min_speakers
    if max_speakers is not None:
        kwargs["max_speakers"] = max_speakers

    diarization_result = _pipeline(audio_path, **kwargs)
    
    # In pyannote-audio 4.x, the pipeline returns a DiarizeOutput object 
    # instead of a raw pyannote.core.Annotation.
    if hasattr(diarization_result, "speaker_diarization"):
        diarization = diarization_result.speaker_diarization
    else:
        diarization = diarization_result

    return [
        (turn.start, turn.end, speaker)
        for turn, _, speaker in diarization.itertracks(yield_label=True)
    ]

def unload_diarizer():
    """Unload the Pyannote model and explicitly free PyTorch/Metal memory."""
    global _pipeline, _pipeline_token
    _pipeline = None
    _pipeline_token = None
    
    import gc
    gc.collect()
    
    # Explicitly clear Metal Performance Shaders (MPS) cache to instantly release GPU VRAM
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    elif torch.backends.mps.is_available():
        torch.mps.empty_cache()
